### ISSUE TITLE
[q] How do you implement clappr plugins?

### ISSUE THREAD

**Issue by TroyKomodo** [vinayakkulkarni/v-clappr#58]
How do you implement clappr plugins that use jquery?

**Comment by vinayakkulkarni** [comment]
> How do you implement clappr plugins that use jquery?

Can you share an example of the plugin you're trying to implement?

**Comment by TroyDota** [comment]
https://github.com/ewwink/clappr-quality-selector-plugin , i realized i can modify it and change the jquery into js.

**Comment by TroyDota** [comment]
Aswell as hlsjs i believe when the clappr is destroyed it doesnt remove events tied to the player. So sometimes switching pages can cause the player to play on an instance that doesnt have a dom element. Very strange.

**Comment by genofire** [comment]
I got exactly the same problem ;(

I believe the problem is here, that every `this.options` is parsed manuelle:
https://github.com/vinayakkulkarni/v-clappr/blob/98bcdd9e19f5f8c496016214708f807c7fe1db0a/src/VClappr.vue#L102-L128

Maybe a merging of the Objects with [assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) solve this problem.
